<a href="https://colab.research.google.com/github/MrBokl/np2022/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота №2
### студента групи Анд-31

### Майданик Андрій

### Варіант №7

# Завдання №1

##### Створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

# Лабораторна робота №2
## студента групи Анд-31

### Майданик Андрій

### Варіант №7
### Завдання №1

створити набір даних із заданим розподілом (розподіл та розмір за власним рішенням), визначити його властивості (shape, rank, size, axis)

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [5]:
Tmatrix = tf.random.Generator.from_seed(42)
Tmatrix = Tmatrix.normal(shape=(5, 5))
print("Tensor list:\n",Tmatrix)
print("Shape of tensor: ", Tmatrix.shape)
print("Rank of tensor:", Tmatrix.ndim)
print("Size  of tensor:", tf.size(Tmatrix).numpy())
print("Elements along axis 0 of tensor:",Tmatrix.shape[0])
print("Elements along axis 1 of tensor:",Tmatrix.shape[1])

Tensor list:
 tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
 [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
 [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.4462975  -2.3410842   0.99009085]
 [-0.0876323  -0.635568   -0.6161736  -1.9441465  -0.48293006]], shape=(5, 5), dtype=float32)
Shape of tensor:  (5, 5)
Rank of tensor: 2
Size  of tensor: 25
Elements along axis 0 of tensor: 5
Elements along axis 1 of tensor: 5


# Завдання №2

продемонструвати основні математичні операції над тензорами.



In [8]:
print("Множення:", Tmatrix * 1.5)

Множення: tf.Tensor(
[[-1.1348704  -0.10282053  0.11392538 -1.8860767  -0.34790644]
 [-2.7161784   0.14983091 -0.7649797  -1.1303707  -0.85749424]
 [ 0.2221161  -0.35044488 -0.5284194   0.609319   -1.5785263 ]
 [ 1.8081896   2.5311732  -0.66944623 -3.5116262   1.4851363 ]
 [-0.13144845 -0.95335203 -0.92426044 -2.9162197  -0.7243951 ]], shape=(5, 5), dtype=float32)


In [15]:
print("Додавання значень: ", Tmatrix + 0.4)

Додавання значень:  tf.Tensor(
[[-0.3565803   0.331453    0.47595027 -0.85738444  0.16806237]
 [-1.4107856   0.4998873  -0.10998645 -0.3535805  -0.17166284]
 [ 0.5480774   0.16637008  0.0477204   0.80621266 -0.6523509 ]
 [ 1.6054597   2.0874488  -0.04629749 -1.9410843   1.3900908 ]
 [ 0.3123677  -0.23556802 -0.21617362 -1.5441465  -0.08293006]], shape=(5, 5), dtype=float32)


In [16]:
print("Віднімання: ", Tmatrix - 0.4)

Віднімання:  tf.Tensor(
[[-1.1565803  -0.46854702 -0.32404974 -1.6573844  -0.6319376 ]
 [-2.2107856  -0.30011272 -0.9099865  -1.1535805  -0.9716629 ]
 [-0.2519226  -0.6336299  -0.75227964  0.00621262 -1.4523509 ]
 [ 0.80545974  1.2874489  -0.8462975  -2.7410843   0.5900909 ]
 [-0.4876323  -1.035568   -1.0161736  -2.3441465  -0.88293004]], shape=(5, 5), dtype=float32)


In [17]:
Tmatrix_aux = tf.random.Generator.from_seed(12)
Tmatrix_aux = Tmatrix_aux.normal(shape=(5, 3))
print("Допоміжний :", Tmatrix_aux)

Допоміжний : tf.Tensor(
[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173  0.8045827 ]
 [ 0.4769051  -0.7812124  -0.996891  ]
 [ 0.33149973 -0.5445254   1.5222508 ]], shape=(5, 3), dtype=float32)


In [18]:
print("множення tensor на tensor: ", tf.matmul(Tmatrix,Tmatrix_aux))

множення tensor на tensor:  tf.Tensor(
[[ 0.10371248  0.8830891   0.08929531]
 [ 1.0237408   0.32776925 -2.7927551 ]
 [-0.62821496  0.14136644 -1.9549872 ]
 [-1.4867893   2.1854858   3.8198607 ]
 [-1.6702008   1.3976151   1.0244255 ]], shape=(5, 3), dtype=float32)


# Завдання №3

### провести CRUD операції над даними, reshape, інтеграцію з np.array, pd.DataFrame.

In [22]:

Vmatrix = tf.Variable([[3,2,3,4],
                      [3,2,3,4],
                      [4,1,2,6]])
print("Update tensor:")
Vmatrix[0].assign([4,1,2,6])

Update tensor:


<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=int32, numpy=
array([[4, 1, 2, 6],
       [3, 2, 3, 4],
       [4, 1, 2, 6]], dtype=int32)>

In [36]:
data = np.array([])
with open("tensor.txt") as f:
    for line in f:
       data = np.append(data,[float(x) for x in line.split()])
TmatrixF = tf.constant(data, shape = (6,2))
print("Upload from file:",TmatrixF)

TypeError: ignored

In [37]:
resh = np.arange(1, 25)
resh

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [38]:
Tmatrix_resh = tf.constant(resh, shape=(6, 4))
Tmatrix_resh

<tf.Tensor: shape=(6, 4), dtype=int64, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [39]:
first_arr = [1, 2, 3, 4, 5, 6, 7, 8]
second_arr = [10, 11, 12, 13, 14, 15, 16 ,17]
df = pd.DataFrame({'fisrt':first_arr,
                  'second':second_arr})
df

fisrt  second
0      1      10
1      2      11
2      3      12
3      4      13
4      5      14
5      6      15
6      7      16
7      8      17

In [40]:
TmatrixD = tf.constant(df)
TmatrixD

<tf.Tensor: shape=(8, 2), dtype=int64, numpy=
array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14],
       [ 6, 15],
       [ 7, 16],
       [ 8, 17]])>

# Висновок

### В ході виконання лабораторної роботи було розглянуто бібліотеку tensorflow. За допомогою цієї бібліотеки ми створювали тензори різного рангу, також розглянули різні види заповнення тензорів. Попрацювали з властивостями та математичними операціями над тензорами. Також провели CRUD операції і зробили інтеграцію з np.array та DataFrame в тензор. Тензор в основному використовують, як ваговы коефіцієнти для навчання нейронних мерж.